apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
  namespace: staging
  labels:
    app: backend
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: farhanraju/biome-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"  
          limits:
            memory: "256Mi"
            cpu: "200m" 
        # ConfigMap se saare variables aik saath load karne ke liye
        envFrom:
        - configMapRef:
            name: backend-config
        # Individual Secrets load karne ke liye
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db-pass
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
