apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-main  
  labels:
    type: local
    env: main  
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-main"
