apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-staging
  namespace: staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
