apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-staging
  labels:
    type: local
    env: staging
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-staging"
